### ISSUE TITLE
Composer conflict in a laravel project

### ISSUE THREAD

**Issue by mathieutu** [tightenco/collect#88] opened 2018-02-22 18:22 UTC
Hi, it's me again! 
After some problems in sf projects, I've them now during a Laravel update.

In fact:

In `mathieutu/exporter` v2.0.0 I'm requiring `tightenco/collect` ^5.6 : https://github.com/mathieutu/exporter/blob/master/composer.json.

With this package in a Laravel project, I can't update `laravel/framework` to 5.6.4 (where the change of collect replace was done):

```
Problem 1
    - mathieutu/exporter 2.0.0 requires tightenco/collect ^5.6 -> satisfiable by laravel/framework[v5.6.3], illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[5.6.4.x-dev, v5.6.0, v5.6.4].
    - mathieutu/exporter 2.0.0 requires tightenco/collect ^5.6 -> satisfiable by laravel/framework[v5.6.3], illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[5.6.4.x-dev, v5.6.0, v5.6.4].
    - Can only install one of: laravel/framework[v5.6.4, v5.6.3].
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.6.4
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.6.4
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.6.4
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.6.4
    - don't install tightenco/collect 5.6.4.x-dev|don't install laravel/framework v5.6.4
    - don't install tightenco/collect v5.6.0|don't install laravel/framework v5.6.4
    - don't install tightenco/collect v5.6.4|don't install laravel/framework v5.6.4
    - Installation request for laravel/framework 5.6.4 -> satisfiable by laravel/framework[v5.6.4].
    - Installation request for mathieutu/exporter ^2.0 -> satisfiable by mathieutu/exporter[2.0.0].
```

If I require tightenco/collect in my root project, it's fine, and I can update. If I remove it, laravel is downgraded to 5.6.3.

Do you guys have any idea of where the problem could come from??

Thank you for your help.

**Comment by mattstauffer** [comment] 2018-02-22 18:48
@mathieutu My guess is this has to do with #76, which we are going to fix going forward.  I MAY be able to also back-release Collect for 5.6.1, 5.6.2, and 5.6.3, which would fix this problem. I'll take a look ASAP.

**Comment by antonioribeiro** [comment] 2018-02-22 20:28
@mathieutu, Collect has no requirement ties with Laravel. Your problem is probably related to something else you have installed.

So I tried installing only your package:

![image](https://user-images.githubusercontent.com/3182864/36562127-ba42ca4c-17f4-11e8-9c68-5c71ffd7fb92.png)

And then required the Framework: 

![image](https://user-images.githubusercontent.com/3182864/36562335-78f8e192-17f5-11e8-90d0-498856b424d0.png)

As you can see, it's all good, it even installed the newly released laravel/framework 5.6.5.

**Comment by antonioribeiro** [comment] 2018-02-22 20:52
Sorry, scratch that. I was able to reproduce your problem, which keeps making no sense. The only tie with Laravel was the `"replace"`, in place only for Collect <5.5.33 now:

https://github.com/laravel/framework/commit/5caa88acde3d8a82fcbb9bbec8dde45dc49d4b7b

**Comment by antonioribeiro** [comment] 2018-02-22 21:10
@mathieutu, @mattstauffer just upgraded it to 5.6.5, and I did a test here with your package and it works fine now.

![image](https://user-images.githubusercontent.com/3182864/36564336-ae582d38-17fb-11e8-8609-fb4a432a8a81.png)

**Comment by mathieutu** [comment] 2018-02-22 21:11
Yeah no problem like that too.
But if you do, like a real case a`composer require laravel/framework` in a empty folder, then `composer require mathieutu/exporter`, you will see the exact same problem (the same if you create-project of laravel/laravel). 
And collect is the only dependency the package has, so I can't see another source of the problem. 
The conflicts occur since version 5.6.4, where we don't replace collect anymore...

``` 
Problem 1
    - Installation request for mathieutu/exporter ^2.0 -> satisfiable by mathieutu/exporter[2.0.0].
    - Conclusion: remove laravel/framework v5.6.5
    - Conclusion: don't install laravel/framework v5.6.5
    - mathieutu/exporter 2.0.0 requires tightenco/collect ^5.6 -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[5.6.4.x-dev, v5.6.0, v5.6.4].
    - Can only install one of: laravel/framework[v5.6.0, v5.6.5].
    - Can only install one of: laravel/framework[v5.6.1, v5.6.5].
    - Can only install one of: laravel/framework[v5.6.2, v5.6.5].
    - Can only install one of: laravel/framework[v5.6.3, v5.6.5].
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.6.5
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.6.5
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.6.5
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.6.5
    - don't install tightenco/collect 5.6.4.x-dev|don't install laravel/framework v5.6.5
    - don't install tightenco/collect v5.6.0|don't install laravel/framework v5.6.5
    - don't install tightenco/collect v5.6.4|don't install laravel/framework v5.6.5
    - Installation request for laravel/framework (locked at v5.6.5, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.5].
```

**Comment by mathieutu** [comment] 2018-02-22 21:17
Sorry didn't see your previous comments @antonioribeiro 
But I've still the pb :/ .
Just try: `mkdir foo && cd foo && cr laravel/framework  && cr mathieutu/exporter`

I think that if it happens to me, it should happens to others package maintainer that use collect.

**Comment by mathieutu** [comment] 2018-02-22 21:22
But as I said, if you `mkdir foo && cd foo && cr laravel/framework && cr tightenco/collect && cr mathieutu/exporter` it works. It needs to have collect as root dependency, and I can't understand why.. 😞

**Comment by antonioribeiro** [comment] 2018-02-22 21:26
Yeah, this dependency resolution is somehow broken. You can try to change the requiremento to `>=5.6.5` instead of `^5.6`, but it's very long shot.

**Comment by antonioribeiro** [comment] 2018-02-22 21:54
Opened an issue in Composer: https://github.com/composer/composer/issues/7129

**Comment by mathieutu** [comment] 2018-02-23 10:04
Ok, I've understood the problem with some similar issues in composer repo, you can check my comment here: https://github.com/composer/composer/issues/7129#issuecomment-367964793

(I don't know where to continue the discussion now 😅)

**Comment by mathieutu** [comment] 2018-02-23 10:09
see https://github.com/composer/composer/pull/3746#issuecomment-74667638 for the explanation about different versions.

So to summarize if I've understood well, the collect package *is not supposed to work anymore with laravel*, because it can't be installed with different version. The fact we can install it in root is probably a bug.

**Comment by antonioribeiro** [comment] 2018-02-23 16:52
Yeah, yesterday I was almost sure it was the `replace`, so I started a test I was just able to finish now. Copied the framework: https://packagist.org/packages/antonioribeiro/framerocks, to try some scenarios:

- [working] `self.version` (which is not an option, we moved from it to `<5.5.33`)
- [working] without `replace`
- [working] using `>=5.5.33` (which works fine, ignoring Collect 5.6.*, but so also not an option)
- [broken] using `<5.5.33` (current one and only broken)

If this is a feature and not a bug, we will have to think a way to make it work.

**Comment by antonioribeiro** [comment] 2018-03-03 16:55
Just sent a new PR to fix it, according [this discussion](https://github.com/composer/composer/issues/7129): https://github.com/laravel/framework/pull/23379

**Comment by mattstauffer** [comment] 2018-03-22 21:05
@antonioribeiro is this good and close-able?

**Comment by antonioribeiro** [comment] 2018-03-22 22:49
Yeah, I think it's definitely fixed now, please close.

**Closed** 2018-03-22 22:50 UTC

**Comment by A-Elshorafa** [comment] 2019-11-12 09:38
I am discover that i am download wronge file for php_mongodb that's for later verison of php

Check that the php_mongodb.dll is for your php version

**Comment by saqib006** [comment] 2020-01-28 05:29
You'll want to make sure you upgrade both the web and cli versions of php to 7.1.2. A lot of times people will only upgrade the web version (and composer will then allow the install), but laravel uses both.
[Free Code Zilla](https://freecodezilla.com)
