### ISSUE TITLE
Namespace change in a bugfix release

### ISSUE THREAD

**Issue by Najki** [tightenco/collect#86] opened 2018-02-22 09:27 UTC
I really hope it's a simple mistake, but it seems that You've changed the namespace from `\Illuminate` to `\Tightenco\Collect` and made minor and bugfix releases including it. 

It's a backward incompatible change which should be released as a major 6.0.0. It broke a lot of my tests in several projects. For now, I'm locking my requirement to 5.5.32.

**Comment by mattstauffer** [comment] 2018-02-22 12:10
There’s a class Ali’s file that *should* be aliasing it to the original illuminate namespaces. Could you give us a little more information about the context where you’re using it so we can try to figure this out?

**Comment by mattstauffer** [comment] 2018-02-22 12:10
*alis

**Comment by mattstauffer** [comment] 2018-02-22 12:11
*alias.  Typing is hard sometimes.

**Comment by Najki** [comment] 2018-02-22 12:31
We pass collections from one place to another on many occasions and we use type hints and return type declarations in PHP 7.1. So the first thing that we saw after upgrading this library to 5.5.33 was a lot of TypeError exceptions in unit tests.

**Comment by antonioribeiro** [comment] 2018-02-22 12:34
I can confirm the bug.

Aliases array should be 

``` php
$aliases = [
    Tightenco\Collect\Contracts\Support\Arrayable::class => Illuminate\Contracts\Support\Arrayable::class,
];
```

instead of 

``` php
$aliases = [
    Illuminate\Contracts\Support\Arrayable::class => Tightenco\Collect\Contracts\Support\Arrayable::class,
];
```

This was one of the reasons I've made that change to damiani's, but I think I got lost discussing a different matter on the same subject.

**Comment by antonioribeiro** [comment] 2018-02-22 14:13
> It's a backward incompatible change which should be released as a major 6.0.0. It broke a lot of my tests in several projects. For now, I'm locking my requirement to 5.5.32.

This package follows Laravel's versions and, by that, also the versioning system, which is not Semver. So, usually we have breaking changes in minor releases, but not on patches, and the namespace change happened on the patch 5.5.33, right before the "major" release to 5.6.0.

I think we could revert the changes in 5.5.33 and retag it, to update the code while keeping the namespace, I have just created a commit in my collect repo to do this: https://github.com/antonioribeiro/collect/commit/1ce247ce4a5d4f450283c9d8d50c4f62fa938fae.

But, I don't think we should wait for Laravel 6.0.0 (it may take 8 years :), nor deviate from Laravel's versioning.

**Comment by mattstauffer** [comment] 2018-02-22 14:57
This will be fixed as soon as Laravel 5.6.5  comes out. I'll have to look into whether it's really possible to re-tag without breaking everything.

**Closed** 2018-02-22 14:57 UTC

**Comment by mattstauffer** [comment] 2018-02-22 14:59
And yah, FWIW, this isn't a backward compatible break; this is a new feature that won't break anything for anyone.. UNLESS there's a bug in implementing it... which we had. Blegh.

Like @antonioribeiro said, we're beholden to Laravel's versioning scheme so we have to work outside of some of the usual constraints of open source packages.

**Comment by antonioribeiro** [comment] 2018-02-22 15:09
@Najki , your Illuminate type hints should work fine when it's released.

**Comment by Najki** [comment] 2018-02-23 13:27
Thanks
