### ISSUE TITLE
Unable to use with Laravel 5.5 through okta/sdk

### ISSUE THREAD

**Issue by LarBearrr** [tightenco/collect#176] opened 2019-08-14 12:33 UTC
I have a Laravel 5.5 application that needs to use [okta/sdk](https://github.com/okta/okta-sdk-php/). When trying to install their latest release, composer says:
```
composer require 'okta/sdk':'1.2.0'                                      ~/Sites/oc-okta
    1/2:        http://repo.packagist.org/p/provider-latest$931036c372fbe3590c8c2636d1dd3cf98af373996e4de279afdfb2d462f9587e.json
    2/2:        http://repo.packagist.org/p/provider-2019-01$295ff58f1da61afb5b4db61b40b610468ad8bfe323a279f4e9f7ed454e44bb1f.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
./composer.json has been updated                           
Loading composer repositories with package information
Updating dependencies (including require-dev)              
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.46
    - don't install tightenco/collect v5.8.31|remove laravel/framework v5.5.46
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.46
    - okta/sdk 1.2.0 requires tightenco/collect 5.8.31 -> satisfiable by tightenco/collect[v5.8.31].
    - Installation request for okta/sdk 1.2.0 -> satisfiable by okta/sdk[1.2.0].
    - Installation request for laravel/framework 5.5.46 -> satisfiable by laravel/framework[v5.5.46]
```
I have contacted Okta, to which they say the issue has been fixed; however, as you can see, there are still problems. Are there any suggestions on how I can work around this issue? 

Any feedback is appreciated, thanks!

**Comment by mattstauffer** [comment] 2019-08-14 12:47
OK, so that's because we require var-dumper 3.4+ and Laravel 5.5 used var-dumper 3.3.

We *may* be able to fix this, I'm not sure.

**Comment by LarBearrr** [comment] 2019-08-14 12:48
Interesting... how long would a fix like this take?

**Comment by mattstauffer** [comment] 2019-08-14 12:49
https://github.com/laravel/framework/blob/0f538802144a41664f545fd92bbb556000cba115/composer.json#L38

Actually.. it's ~3.3, which as far as I know would allow for 3.4, which we required as a minimum.

Just a random idea, because I'm not the king of Composeer; can you delete your composer.lock file, add the okta package to your composer.json, and try a fresh `composer install` (do this on a branch so you don't mess anything up) just to see what happens?

**Comment by mattstauffer** [comment] 2019-08-14 12:50
If it *is* a bug, it'll take as long as it takes. :) This is an open source package, not a commercial one, so there's no guarantee of bug fixes or "uptime". It's run by people volunteering their time (some of whom work at tighten, some of whom don't).

**Comment by LarBearrr** [comment] 2019-08-14 12:55
Sure, I totally understand and I wasn't meaning to come off pushy. Just trying to figure out what I need to do to meet a #deadline. 

I just tried your suggestion and `okta/sdk` will install; however, your package does not get brought in. I'm not sure if it is an issue but Laravel's composer "replaces" your package: https://github.com/laravel/framework/blob/5.5/composer.json#L71

I may need to fork their repo and modify as needed.

**Comment by mattstauffer** [comment] 2019-08-14 12:57
Ahh.. yah... we got rid of that replace because of this exact issue.

I would try explicitly requiring the collect package in your repo. Let me know if that helps.

No worries about being pushy, sorry to be defensive. :)

**Comment by LarBearrr** [comment] 2019-08-14 13:02
TBH, I'm slighly disappointed in the level of support and code quality from Okta. That being said, if I use their `1.0.0` release, which actually uses Laravel's Support module for collections, it will install. However, their implementation of the `operatorForWhere` method does not match the expected footprint from Support:
```
Declaration of Okta\Resource\AbstractCollection::operatorForWhere($key, $operator, $value) should be compatible with Illuminate\Support\Collection::operatorForWhere($key, $operator, $value = NULL)
```

A quick update to their source fixes the issue 🤔

**Comment by mattstauffer** [comment] 2019-08-14 13:02
Yah, the problem is, it needs to work both on 5.5 apps AND 5.8 apps, which is where this problem arises.

**Comment by LarBearrr** [comment] 2019-08-14 13:04
Back to your previous suggestion, do you know the composer command to bring in your version that would be compatible with 5.5?

**Comment by mattstauffer** [comment] 2019-08-14 13:07
Ours is compatible with 5.5, actually. 

```
composer require tightenco/collect:5.8.31
```

**Comment by LarBearrr** [comment] 2019-08-14 13:12
Hmm...
```
λ lb-test-okta $ composer require tightenco/collect:5.8.31                                  ~/Sites/overdrive
    1/1:        http://repo.packagist.org/p/provider-latest$c30582afa1283e82056b124e457ec77cc3e275de4f54c81b6fe7803acdb4f0f1.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install tightenco/collect v5.8.31|don't install laravel/framework 5.5.x-dev
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.0
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.1
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.10
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.11
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.12
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.13
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.14
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.15
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.16
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.17
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.18
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.19
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.2
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.20
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.21
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.22
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.23
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.24
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.25
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.26
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.27
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.28
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.29
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.3
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.30
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.31
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.32
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.33
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.34
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.35
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.36
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.37
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.38
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.39
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.4
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.41
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.43
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.44
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.45
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.46
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.47
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.5
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.6
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.7
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.8
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.9
    - don't install tightenco/collect v5.8.31|remove laravel/framework v5.5.47
    - don't install tightenco/collect v5.8.31|don't install laravel/framework v5.5.47
    - Installation request for tightenco/collect 5.8.31 -> satisfiable by tightenco/collect[v5.8.31].
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev, v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.40, v5.5.41, v5.5.42, v5.5.43, v5.5.44, v5.5.45, v5.5.46, v5.5.47, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by mattstauffer** [comment] 2019-08-14 13:16
@LarBearrr Can you delete your `composer.lock`, add this `tightenco/collect` to your `composer.json`, and then composer install?

**Comment by LarBearrr** [comment] 2019-08-14 13:18
Unfortunately that doesn't do it either, same issue.

**Comment by mattstauffer** [comment] 2019-08-14 13:24
huh. We have a very, very small require block so I'm really surprised by that:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/151829/63024241-d75a1680-be74-11e9-98e6-21fe781b4807.png">

Would you try this constraint instead?

```
        "tightenco/collect": "dev-mes/testing-no-dumper-for-larbearrr",
```

And then do the same thing? I just pulled out the var dumper to see if that's the issue.

**Comment by LarBearrr** [comment] 2019-08-14 13:31
Same 😞 Terribly sorry to be eating up so much of your time!

**Comment by mattstauffer** [comment] 2019-08-14 13:40
That's... really weird. I can't for the life of me figure out what would conflict, honestly.

**Comment by LarBearrr** [comment] 2019-08-14 13:43
Me either.. I've spent nearly a week trying to figure this out and it's driving me up the wall. Like I said, Okta hasn't been very responsive except to say basically "works on my machine." Anyhow, I don't expect you to spend a ton of time on it. Worst case I can fork their repo and make the changes I need to get by. I certainly appreciate your responsiveness and time. Do let me know if something changes though!

**Comment by mattstauffer** [comment] 2019-08-14 13:46
@LarBearrr could you do me a favor? Could you write in a comment here the full writeup of your *current* situation? Like:

"Here's my composer.json. Here's my PHP verison. I deleted my composer.lock and vendor folder, added this branch matt made for me, ran composer install, and here's the error I got."

Then I can ask around a bit pointing straight to that comment.

**Comment by LarBearrr** [comment] 2019-08-14 13:59
Sure, thanks for your willingness to look into it. It also may be helpful to know the framework I'm using: [OctoberCMS Composer Install](https://octobercms.com/docs/console/commands#console-install-composer)

`composer.json`:
```
{
    "name": "",
    "description": "",
    "homepage": "",
    "keywords": [
    ],
    "authors": [
        {
            "name": "Larry Barker",
            "homepage": "https://www.bgprod.com/",
            "role": "Backend Developer"
        }
    ],
    "require": {
        "php": ">=7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "october/rain": "dev-develop as 1.0",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",
        "laravel/framework": "5.5.*@dev",
        "wikimedia/composer-merge-plugin": "dev-master",
        "rainlab/sitemap-plugin": "dev-master",
        "rainlab/location-plugin": "dev-master",
        "renatio/dynamicpdf-plugin": "dev-master",
        "october/drivers-plugin": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "^1.8",
        "phpunit/phpunit": "~5.7",
        "phpunit/phpunit-selenium": "~1.2",
        "meyfa/phpunit-assert-gd": "1.1.0",
        "rainlab/builder-plugin": "dev-master",
        "bedard/debugbar": "^2.0"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-update-cmd": [
            "php artisan october:util set build"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}
```

PHP Version (machine): 7.3
PHP Version (composer?): >= 7.0

So far, I have tried:

1. `composer require okta/sdk` with the existing `composer.lock` in place, which produces the following messages:
```
λ lb-test-okta $ composer require okta/sdk                                                  ~/Sites/overdrive
    1/4:        http://repo.packagist.org/p/provider-latest$bfc1f3acab70d7439a89218ba6fcb2d6b7757f42e591ca39e4a09c1d55a73bc2.json
    2/4:        http://repo.packagist.org/p/provider-2019-07$287cfa15b6202cdb100646385931026692bb45d750ff09155569b1813886e436.json
    3/4:        http://repo.packagist.org/p/provider-2019-04$5d55e6f96a0c3a5b55e0ed4ff8255f60e5d790c5c52d3da36e2ba19f1ec1a98a.json
    4/4:        http://repo.packagist.org/p/provider-2018$5cfc0ad759c53c1ed59af151e0333507fb9343ff07a14d9aef487deb46f1787a.json
    Finished: success: 4, skipped: 0, failure: 0, total: 4
Using version ^1.1 for okta/sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for okta/sdk ^1.1 -> satisfiable by okta/sdk[1.1.0].
    - Conclusion: remove laravel/framework v5.5.47
    - Conclusion: don't install laravel/framework v5.5.47
    - okta/sdk 1.1.0 requires tightenco/collect 5.5.33 -> satisfiable by illuminate/support[v5.5.33], laravel/framework[v5.5.33], tightenco/collect[v5.5.33].
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.5.47
    - Can only install one of: laravel/framework[v5.5.33, v5.5.47].
    - don't install tightenco/collect v5.5.33|don't install laravel/framework v5.5.47
    - Installation request for laravel/framework (locked at v5.5.47, required as 5.5.*@dev) -> satisfiable by laravel/framework[v5.5.47].


Installation failed, reverting ./composer.json to its original content.
```

2. I have also tried deleting my `composer.lock` and manually adding `okta/sdk` to my `composer.json` as `"okta/sdk": "dev-develop"` which includes their updates to use the latest `tightenco/collect`. See [#L62](https://github.com/okta/okta-sdk-php/blob/develop/composer.json#L22). This doesn't produce any errors but the package is not actually installed. 

3. My most recent attempts have involved following the suggestions by @mattstauffer here. Namely, deleting `composer.lock` and manually adding various versions ("tightenco/collect": "5.8.31") of `tightenco/collect` to `composer.json`. This produces the error found in [this comment](https://github.com/tightenco/collect/issues/176#issuecomment-521239724).

4. The closest I have been able to get is to use their `1.0.0` release; however, this version does not actually require `tightenco/collect` and produces declaration issues with their implementation of the `operatorForWhere` method as [mentioned above](https://github.com/tightenco/collect/issues/176#issuecomment-521236193).

I have also opened [an issue in Okta's repo](https://github.com/okta/okta-sdk-php/issues/63) if you're interested. That's about as far I have gotten so far. Any feedback or assistance is greatly appreciated.

**Comment by DanielCoulbourne** [comment] 2019-08-14 15:36
@LarBearrr It appears you may have an extra composer.json being merged in according to this block
```
"extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
```

Could you edit your above comment to  include that as well?

**Comment by LarBearrr** [comment] 2019-08-15 12:42
@DanielCoulbourne Thanks for the reply. The framework I'm using (OctoberCMS), uses plugins that may have their own dependencies. I would have to include the composer.json files for each plugin, which seems cumbersome. I also don't think any of these are causing the issue as I have tried with a fresh install of October and still have issues. This problem also exists with vanilla Laravel applications which tells me it is not related to any of my plugin's composer.json files. If you'd still like to see the other composer.json files let me know and I will share.

**Comment by mattstauffer** [comment] 2019-08-15 13:08
@LarBearrr My suspicion based on a quick test @loganhenson ran for me yesterday is that it's the specific version constraint that the Okta package used that's the issue. Let me take a look at that and get back to you.

**Comment by mattstauffer** [comment] 2019-08-15 18:02
@LarBearrr OK, so I just tried this on a local Laravel 5.5 repo:

```
rm composer.lock
rm -rf vendor
composer require okta/sdk
```

And it worked for me. So let's start there.

Dropping both the lock and the vendor folder, strangely, has an impact on what it thinks it already has installed.

**Comment by LarBearrr** [comment] 2019-08-15 18:06
@mattstauffer Very interesting... I appreciate you taking so much time to look into this. I'll have to buy you a coffee @ Laracon next year 😄 Let me see if I can get as far as you. My only concern is how this plays out when it's time to deploy to production?

**Comment by mattstauffer** [comment] 2019-08-15 18:12
If you get it fixed in your `composer.lock` file in version control, that'll push up to production with no issue. :) Coffee sounds great! :D @loganhenson is also helping me out behind the scenes here. :)

**Comment by LarBearrr** [comment] 2019-08-15 18:14
Just out of curiosity, have you ever integrated with Okta before?

**Comment by mattstauffer** [comment] 2019-08-15 18:14
Nope :)

**Comment by LarBearrr** [comment] 2019-08-15 18:15
Fair enough, is there a better channel to reach you at for DM/PM? I'll circle back here later this evening with an update.

**Comment by mattstauffer** [comment] 2019-08-15 19:17
@LarBearrr Laravel Discord maybe? Or just here ¯\(°_o)/¯

**Comment by LarBearrr** [comment] 2019-10-11 02:06
@mattstauffer Thanks for your time trying to work through this with me. I've managed to get a workaround using `v1.0.0` of Okta's package and `class_alias()` to trick it into using `Illuminate\Support\Collection`. I'm going to close unless you want to keep open?

**Comment by mattstauffer** [comment] 2019-10-11 17:03
@LarBearrr I think so--I don't think I was able to reproduce it with a plain install so let's call it good until someone else runs into it. Thanks!!

**Closed by mattstauffer** 2019-10-11 17:03 UTC
