### ISSUE TITLE
illuminate/collections exists: what now?

### ISSUE THREAD

**Issue by austinpray** [tightenco/collect#236] opened 2020-08-02 20:07 UTC
Now [illuminate/collections](https://github.com/illuminate/collections) exists. So far looks like it's a drop-in replacement for this package. [illuminate/collections](https://github.com/illuminate/collections) even solves [some problems](https://github.com/tightenco/collect/issues/199#issuecomment-619422506) I have with this package.

According to [the Readme](https://github.com/tightenco/collect/tree/e070bf74564f311bb3c97e673e97ea036b38a449#faq):

>One day Collection may be extracted from illuminate/support to a new package. If so, we'll deprecate this package and point to the core version.

**Comment by mattstauffer** [comment] 2020-08-03 14:12
Thanks @austinpray! Closing as a duplicate of https://github.com/tightenco/collect/issues/217

**Closed as completed by mattstauffer** 2020-08-03 14:12 UTC

**Comment by austinpray** [comment] 2020-08-03 14:31
@mattstauffer Ah! Thank you! That discussion was exactly what I was looking for :+1:
